/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: BrandXR (https://sketchfab.com/brandxr)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/davita-finish-line-2020-003d816301084f719897503bdb4ffbc3
title: Davita Finish-Line 2020
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function FinishLine1(props) {
  const { nodes, materials } = useGLTF(
    '/finish-line/davita_finish-line_2020.glb'
  )
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, -1.07]} scale={0.67}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6.geometry}
              material={materials.material}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/finish-line/davita_finish-line_2020.glb')

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: amogusstrikesback (https://sketchfab.com/amogusstrikesback)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/hiberworld-alternate-goal-finish-line-4b189ebf10a944399b884fcc6784cabf
title: hiberworld alternate goal (finish line)
*/

export function FinishLine2(props) {
  const { nodes, materials } = useGLTF(
    '/finish-line/hiberworld_alternate_goal_finish_line.glb'
  )
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.GPL_goal_02_Material006_0.geometry}
              material={materials['Material.006']}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/finish-line/hiberworld_alternate_goal_finish_line.glb')
